### GET USERS
# @name get all users
GET http://localhost:8080/api/v1/users
Accept: application/json

### CREATE a USER
# @name create a new  user
POST http://localhost:8080/api/v1/users
Accept: application/json
Content-Type: application/json

{
  "email": "test@test.test",
  "fullName": "Test Name"
}

### GET USER BY ID
# @name get user by id
GET http://localhost:8080/api/v1/users/1
Accept: application/json
Content-Type: application/json
